-- CreateTable
CREATE TABLE `kriteria` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA` VARCHAR(255) NOT NULL,
    `BOBOT` DECIMAL(5, 2) NOT NULL,
    `JENIS` ENUM('cost', 'benefit') NOT NULL,

    UNIQUE INDEX `NAMA`(`NAMA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `penilaian` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SISWA_ID` INTEGER NOT NULL,
    `KRITERIA_ID` INTEGER NOT NULL,
    `NILAI` DECIMAL(5, 2) NOT NULL,

    INDEX `KRITERIA_ID`(`KRITERIA_ID`),
    UNIQUE INDEX `SISWA_ID`(`SISWA_ID`, `KRITERIA_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `siswa` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA` VARCHAR(255) NOT NULL,
    `NIS` VARCHAR(255) NOT NULL,
    `KELAS` VARCHAR(255) NOT NULL,
    `NAMA_ORANG_TUA` VARCHAR(255) NULL,
    `ALAMAT` TEXT NULL,

    UNIQUE INDEX `NIS`(`NIS`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAMA` VARCHAR(255) NOT NULL,
    `USERNAME` VARCHAR(255) NOT NULL,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `ROLE` ENUM('admin', 'guru', 'kepala sekolah') NOT NULL,

    UNIQUE INDEX `USERNAME`(`USERNAME`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `penilaian` ADD CONSTRAINT `penilaian_SISWA_ID_fkey` FOREIGN KEY (`SISWA_ID`) REFERENCES `siswa`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `penilaian` ADD CONSTRAINT `penilaian_KRITERIA_ID_fkey` FOREIGN KEY (`KRITERIA_ID`) REFERENCES `kriteria`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
