CREATE DATABASE IF NOT EXISTS `SPK_DB`;

USE `SPK_DB`;

CREATE TABLE IF NOT EXISTS `USER` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NAMA` VARCHAR(255) NOT NULL,
    `USERNAME` VARCHAR(255) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(255) NOT NULL,
    `ROLE` ENUM('admin', 'guru', 'kepala sekolah') NOT NULL
);

CREATE TABLE IF NOT EXISTS `SISWA` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NAMA` VARCHAR(255) NOT NULL,
    `NIS` VARCHAR(255) NOT NULL UNIQUE,
    `KELAS` VARCHAR(255) NOT NULL,
    `NAMA_ORANG_TUA` VARCHAR(255),
    `ALAMAT` TEXT
);

CREATE TABLE IF NOT EXISTS `KRITERIA` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `NAMA` VARCHAR(255) NOT NULL UNIQUE,
    `BOBOT` DECIMAL(5, 2) NOT NULL,
    `JENIS` ENUM('cost', 'benefit') NOT NULL
);

CREATE TABLE IF NOT EXISTS `PENILAIAN` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `SISWA_ID` INT NOT NULL,
    `KRITERIA_ID` INT NOT NULL,
    `NILAI` DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (`SISWA_ID`) REFERENCES `SISWA`(`ID`) ON DELETE CASCADE,
    FOREIGN KEY (`KRITERIA_ID`) REFERENCES `KRITERIA`(`ID`) ON DELETE CASCADE,
    UNIQUE (`SISWA_ID`, `KRITERIA_ID`)
);